[package]
name = "inx-eddn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota-wallet = "1.0.0-rc.6"
zmq = "0.10.0"
tokio = { version = "1.21.2", features = ["full"] }
async-recursion = "1.0.0"
flate2 = { version = "1.0.24", features = ["zlib-ng"], default-features = false }
dotenv = "0.15.0"
json = "0.12.4"
serde_json = "1.0.94"
bus = "2.3.0"
